#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : open_model_zoo
Version  : 2019.r3.1
Release  : 5
URL      : https://github.com/opencv/open_model_zoo/archive/2019_R3.1/open_model_zoo-2019.R3.1.tar.gz
Source0  : https://github.com/opencv/open_model_zoo/archive/2019_R3.1/open_model_zoo-2019.R3.1.tar.gz
Summary  : @PACKAGE_DESCRIPTION@
Group    : Development/Tools
License  : Apache-2.0 BSD-3-Clause
Requires: open_model_zoo-bin = %{version}-%{release}
Requires: open_model_zoo-data = %{version}-%{release}
Requires: open_model_zoo-license = %{version}-%{release}
Requires: Pillow
Requires: numpy
Requires: scipy
BuildRequires : Pillow
BuildRequires : buildreq-cmake
BuildRequires : buildreq-distutils3
BuildRequires : numpy
BuildRequires : scipy

%description
# [OpenVINO™ Toolkit](https://01.org/openvinotoolkit) - Open Model Zoo repository
[![Build Status](http://134.191.240.124/buildStatus/icon?job=omz/2018/trigger)](http://134.191.240.124/job/omz/job/2018/job/trigger/)
[![Stable release](https://img.shields.io/badge/version-2019_R3.1-green.svg)](https://github.com/opencv/open_model_zoo/releases/tag/2019_R3.1)
[![Gitter chat](https://badges.gitter.im/gitterHQ/gitter.png)](https://gitter.im/open_model_zoo/community)
[![Apache License Version 2.0](https://img.shields.io/badge/license-Apache_2.0-green.svg)](LICENSE)

%package bin
Summary: bin components for the open_model_zoo package.
Group: Binaries
Requires: open_model_zoo-data = %{version}-%{release}
Requires: open_model_zoo-license = %{version}-%{release}

%description bin
bin components for the open_model_zoo package.


%package data
Summary: data components for the open_model_zoo package.
Group: Data

%description data
data components for the open_model_zoo package.


%package license
Summary: license components for the open_model_zoo package.
Group: Default

%description license
license components for the open_model_zoo package.


%prep
%setup -q -n open_model_zoo-2019_R3.1
cd %{_builddir}/open_model_zoo-2019_R3.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1604903852
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
make  %{?_smp_mflags}  || :


%install
export SOURCE_DATE_EPOCH=1604903852
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/open_model_zoo
cp %{_builddir}/open_model_zoo-2019_R3.1/LICENSE %{buildroot}/usr/share/package-licenses/open_model_zoo/7df059597099bb7dcf25d2a9aedfaf4465f72d8d
cp %{_builddir}/open_model_zoo-2019_R3.1/demos/thirdparty/gflags/COPYING.txt %{buildroot}/usr/share/package-licenses/open_model_zoo/b2d4ab17f1b8ef9e0646ba932dce81efe3b852ab
cp %{_builddir}/open_model_zoo-2019_R3.1/models/intel/LICENSE %{buildroot}/usr/share/package-licenses/open_model_zoo/7df059597099bb7dcf25d2a9aedfaf4465f72d8d
cp %{_builddir}/open_model_zoo-2019_R3.1/tools/downloader/license.txt %{buildroot}/usr/share/package-licenses/open_model_zoo/b3e1bac179417a8acb7aca742178befb9b18950d
:
## install_append content
mkdir -p %{buildroot}/usr/share/open_model_zoo
cp -ar models %{buildroot}/usr/share/open_model_zoo/
cp -ar tools %{buildroot}/usr/share/open_model_zoo/
mkdir -p %{buildroot}/usr/bin
ln -s /usr/share/open_model_zoo/tools/downloader/downloader.py %{buildroot}/usr/bin/model-downloader
ln -s /usr/share/open_model_zoo/tools/downloader/converter.py %{buildroot}/usr/bin/model-converter

## install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/model-converter
/usr/bin/model-downloader

%files data
%defattr(-,root,root,-)
/usr/share/open_model_zoo/models/intel/LICENSE
/usr/share/open_model_zoo/models/intel/action-recognition-0001-decoder/description/action-recognition-0001-decoder.md
/usr/share/open_model_zoo/models/intel/action-recognition-0001-decoder/description/demo.png
/usr/share/open_model_zoo/models/intel/action-recognition-0001-decoder/model.yml
/usr/share/open_model_zoo/models/intel/action-recognition-0001-encoder/description/action-recognition-0001-encoder.md
/usr/share/open_model_zoo/models/intel/action-recognition-0001-encoder/description/demo.png
/usr/share/open_model_zoo/models/intel/action-recognition-0001-encoder/model.yml
/usr/share/open_model_zoo/models/intel/age-gender-recognition-retail-0013/age-gender-recognition-retail-0013.prototxt
/usr/share/open_model_zoo/models/intel/age-gender-recognition-retail-0013/description/age-gender-recognition-retail-0001.jpg
/usr/share/open_model_zoo/models/intel/age-gender-recognition-retail-0013/description/age-gender-recognition-retail-0002.png
/usr/share/open_model_zoo/models/intel/age-gender-recognition-retail-0013/description/age-gender-recognition-retail-0003.png
/usr/share/open_model_zoo/models/intel/age-gender-recognition-retail-0013/description/age-gender-recognition-retail-0013.md
/usr/share/open_model_zoo/models/intel/age-gender-recognition-retail-0013/model.yml
/usr/share/open_model_zoo/models/intel/driver-action-recognition-adas-0002-decoder/description/action-recognition-kelly.png
/usr/share/open_model_zoo/models/intel/driver-action-recognition-adas-0002-decoder/description/driver-action-recognition-adas-0002-decoder.md
/usr/share/open_model_zoo/models/intel/driver-action-recognition-adas-0002-decoder/model.yml
/usr/share/open_model_zoo/models/intel/driver-action-recognition-adas-0002-encoder/description/action-recognition-kelly.png
/usr/share/open_model_zoo/models/intel/driver-action-recognition-adas-0002-encoder/description/driver-action-recognition-adas-0002-encoder.md
/usr/share/open_model_zoo/models/intel/driver-action-recognition-adas-0002-encoder/model.yml
/usr/share/open_model_zoo/models/intel/emotions-recognition-retail-0003/description/emotions-recognition-retail-0003.jpg
/usr/share/open_model_zoo/models/intel/emotions-recognition-retail-0003/description/emotions-recognition-retail-0003.md
/usr/share/open_model_zoo/models/intel/emotions-recognition-retail-0003/emotions-recognition-retail-0003.prototxt
/usr/share/open_model_zoo/models/intel/emotions-recognition-retail-0003/model.yml
/usr/share/open_model_zoo/models/intel/face-detection-adas-0001/description/face-detection-adas-0001.md
/usr/share/open_model_zoo/models/intel/face-detection-adas-0001/description/face-detection-adas-0001.png
/usr/share/open_model_zoo/models/intel/face-detection-adas-0001/face-detection-adas-0001.prototxt
/usr/share/open_model_zoo/models/intel/face-detection-adas-0001/model.yml
/usr/share/open_model_zoo/models/intel/face-detection-adas-binary-0001/description/face-detection-adas-binary-0001.md
/usr/share/open_model_zoo/models/intel/face-detection-adas-binary-0001/description/face-detection-adas-binary-0001.png
/usr/share/open_model_zoo/models/intel/face-detection-adas-binary-0001/model.yml
/usr/share/open_model_zoo/models/intel/face-detection-retail-0004/description/face-detection-retail-0001.png
/usr/share/open_model_zoo/models/intel/face-detection-retail-0004/description/face-detection-retail-0004.md
/usr/share/open_model_zoo/models/intel/face-detection-retail-0004/face-detection-retail-0004.prototxt
/usr/share/open_model_zoo/models/intel/face-detection-retail-0004/model.yml
/usr/share/open_model_zoo/models/intel/face-detection-retail-0005/description/face-detection-retail-0001.png
/usr/share/open_model_zoo/models/intel/face-detection-retail-0005/description/face-detection-retail-0005.md
/usr/share/open_model_zoo/models/intel/face-detection-retail-0005/model.yml
/usr/share/open_model_zoo/models/intel/face-reidentification-retail-0095/description/face-reidentification-retail-0095.md
/usr/share/open_model_zoo/models/intel/face-reidentification-retail-0095/description/face-reidentification-retail-0095.png
/usr/share/open_model_zoo/models/intel/face-reidentification-retail-0095/model.yml
/usr/share/open_model_zoo/models/intel/facial-landmarks-35-adas-0002/description/error_formula.png
/usr/share/open_model_zoo/models/intel/facial-landmarks-35-adas-0002/description/facial-landmarks-35-adas-0002.md
/usr/share/open_model_zoo/models/intel/facial-landmarks-35-adas-0002/description/landmarks_illustration.png
/usr/share/open_model_zoo/models/intel/facial-landmarks-35-adas-0002/facial-landmarks-35-adas-0002.prototxt
/usr/share/open_model_zoo/models/intel/facial-landmarks-35-adas-0002/model.yml
/usr/share/open_model_zoo/models/intel/gaze-estimation-adas-0002/description/gaze-estimation-adas-0002.md
/usr/share/open_model_zoo/models/intel/gaze-estimation-adas-0002/description/ill_for_gaze.png
/usr/share/open_model_zoo/models/intel/gaze-estimation-adas-0002/model.yml
/usr/share/open_model_zoo/models/intel/handwritten-score-recognition-0003/description/handwritten-score-recognition-0003.md
/usr/share/open_model_zoo/models/intel/handwritten-score-recognition-0003/description/shot_25.png
/usr/share/open_model_zoo/models/intel/handwritten-score-recognition-0003/model.yml
/usr/share/open_model_zoo/models/intel/head-pose-estimation-adas-0001/description/head-pose-estimation-adas-0001.md
/usr/share/open_model_zoo/models/intel/head-pose-estimation-adas-0001/description/head-pose-estimation-adas-0001.png
/usr/share/open_model_zoo/models/intel/head-pose-estimation-adas-0001/head-pose-estimation-adas-0001.prototxt
/usr/share/open_model_zoo/models/intel/head-pose-estimation-adas-0001/model.yml
/usr/share/open_model_zoo/models/intel/human-pose-estimation-0001/description/human-pose-estimation-0001.md
/usr/share/open_model_zoo/models/intel/human-pose-estimation-0001/description/human-pose-estimation-0001.png
/usr/share/open_model_zoo/models/intel/human-pose-estimation-0001/human-pose-estimation-0001.prototxt
/usr/share/open_model_zoo/models/intel/human-pose-estimation-0001/model.yml
/usr/share/open_model_zoo/models/intel/image-retrieval-0001/description/image-retrieval-0001.jpg
/usr/share/open_model_zoo/models/intel/image-retrieval-0001/description/image-retrieval-0001.md
/usr/share/open_model_zoo/models/intel/image-retrieval-0001/model.yml
/usr/share/open_model_zoo/models/intel/inceptionv3-int8-sparse-v1-tf-0001/description/inceptionv3-int8-sparse-v1-tf-0001.md
/usr/share/open_model_zoo/models/intel/inceptionv3-int8-sparse-v1-tf-0001/model.yml
/usr/share/open_model_zoo/models/intel/inceptionv3-int8-sparse-v2-tf-0001/description/inceptionv3-int8-sparse-v2-tf-0001.md
/usr/share/open_model_zoo/models/intel/inceptionv3-int8-sparse-v2-tf-0001/model.yml
/usr/share/open_model_zoo/models/intel/inceptionv3-int8-tf-0001/description/inceptionv3-int8-tf-0001.md
/usr/share/open_model_zoo/models/intel/inceptionv3-int8-tf-0001/model.yml
/usr/share/open_model_zoo/models/intel/index.md
/usr/share/open_model_zoo/models/intel/instance-segmentation-security-0010/description/instance-segmentation-security-0010.md
/usr/share/open_model_zoo/models/intel/instance-segmentation-security-0010/description/instance-segmentation-security-0010.png
/usr/share/open_model_zoo/models/intel/instance-segmentation-security-0010/model.yml
/usr/share/open_model_zoo/models/intel/instance-segmentation-security-0050/description/instance-segmentation-security-0050.md
/usr/share/open_model_zoo/models/intel/instance-segmentation-security-0050/description/instance-segmentation-security-0050.png
/usr/share/open_model_zoo/models/intel/instance-segmentation-security-0050/model.yml
/usr/share/open_model_zoo/models/intel/instance-segmentation-security-0083/description/instance-segmentation-security-0083.md
/usr/share/open_model_zoo/models/intel/instance-segmentation-security-0083/description/instance-segmentation-security-0083.png
/usr/share/open_model_zoo/models/intel/instance-segmentation-security-0083/model.yml
/usr/share/open_model_zoo/models/intel/intel_logo.png
/usr/share/open_model_zoo/models/intel/intel_styles.css
/usr/share/open_model_zoo/models/intel/landmarks-regression-retail-0009/description/landmarks-regression-retail-0009.md
/usr/share/open_model_zoo/models/intel/landmarks-regression-retail-0009/description/landmarks-regression-retail-0009.png
/usr/share/open_model_zoo/models/intel/landmarks-regression-retail-0009/description/normed_error.png
/usr/share/open_model_zoo/models/intel/landmarks-regression-retail-0009/model.yml
/usr/share/open_model_zoo/models/intel/license-plate-recognition-barrier-0001/description/license-plate-recognition-barrier-0001.md
/usr/share/open_model_zoo/models/intel/license-plate-recognition-barrier-0001/description/license-plate-recognition-barrier-0001.png
/usr/share/open_model_zoo/models/intel/license-plate-recognition-barrier-0001/license-plate-recognition-barrier-0001.prototxt
/usr/share/open_model_zoo/models/intel/license-plate-recognition-barrier-0001/model.yml
/usr/share/open_model_zoo/models/intel/mobilenetv2-int8-sparse-v1-tf-0001/description/mobilenetv2-int8-sparse-v1-tf-0001.md
/usr/share/open_model_zoo/models/intel/mobilenetv2-int8-sparse-v1-tf-0001/model.yml
/usr/share/open_model_zoo/models/intel/mobilenetv2-int8-sparse-v2-tf-0001/description/mobilenetv2-int8-sparse-v2-tf-0001.md
/usr/share/open_model_zoo/models/intel/mobilenetv2-int8-sparse-v2-tf-0001/model.yml
/usr/share/open_model_zoo/models/intel/mobilenetv2-int8-tf-0001/description/mobilenetv2-int8-tf-0001.md
/usr/share/open_model_zoo/models/intel/mobilenetv2-int8-tf-0001/model.yml
/usr/share/open_model_zoo/models/intel/pedestrian-and-vehicle-detector-adas-0001/description/pedestrian-and-vehicle-detector-adas-0001.md
/usr/share/open_model_zoo/models/intel/pedestrian-and-vehicle-detector-adas-0001/description/pedestrian-and-vehicle-detector-adas-0001.png
/usr/share/open_model_zoo/models/intel/pedestrian-and-vehicle-detector-adas-0001/model.yml
/usr/share/open_model_zoo/models/intel/pedestrian-and-vehicle-detector-adas-0001/pedestrian-and-vehicle-detector-adas-0001.prototxt
/usr/share/open_model_zoo/models/intel/pedestrian-detection-adas-0002/description/pedestrian-detection-adas-0002.md
/usr/share/open_model_zoo/models/intel/pedestrian-detection-adas-0002/description/pedestrian-detection-adas-0002.png
/usr/share/open_model_zoo/models/intel/pedestrian-detection-adas-0002/model.yml
/usr/share/open_model_zoo/models/intel/pedestrian-detection-adas-0002/pedestrian-detection-adas-0002.prototxt
/usr/share/open_model_zoo/models/intel/pedestrian-detection-adas-binary-0001/description/pedestrian-detection-adas-binary-0001.md
/usr/share/open_model_zoo/models/intel/pedestrian-detection-adas-binary-0001/description/pedestrian-detection-adas-binary-0001.png
/usr/share/open_model_zoo/models/intel/pedestrian-detection-adas-binary-0001/model.yml
/usr/share/open_model_zoo/models/intel/person-attributes-recognition-crossroad-0230/description/person-attributes-recognition-crossroad-0230.md
/usr/share/open_model_zoo/models/intel/person-attributes-recognition-crossroad-0230/description/person-attributes-recognition-crossroad-230-1.png
/usr/share/open_model_zoo/models/intel/person-attributes-recognition-crossroad-0230/description/person-attributes-recognition-crossroad-230-2.png
/usr/share/open_model_zoo/models/intel/person-attributes-recognition-crossroad-0230/description/person-attributes-recognition-crossroad-230-3.png
/usr/share/open_model_zoo/models/intel/person-attributes-recognition-crossroad-0230/description/person-attributes-recognition-crossroad-230-4.png
/usr/share/open_model_zoo/models/intel/person-attributes-recognition-crossroad-0230/description/person-attributes-recognition-crossroad-230-5.png
/usr/share/open_model_zoo/models/intel/person-attributes-recognition-crossroad-0230/model.yml
/usr/share/open_model_zoo/models/intel/person-detection-action-recognition-0005/description/person-detection-action-recognition-0005.md
/usr/share/open_model_zoo/models/intel/person-detection-action-recognition-0005/description/person-detection-action-recognition-0005.png
/usr/share/open_model_zoo/models/intel/person-detection-action-recognition-0005/model.yml
/usr/share/open_model_zoo/models/intel/person-detection-action-recognition-0005/person-detection-action-recognition-0005.prototxt
/usr/share/open_model_zoo/models/intel/person-detection-action-recognition-0006/description/person-detection-action-recognition-0006.md
/usr/share/open_model_zoo/models/intel/person-detection-action-recognition-0006/description/person-detection-action-recognition-0006.png
/usr/share/open_model_zoo/models/intel/person-detection-action-recognition-0006/model.yml
/usr/share/open_model_zoo/models/intel/person-detection-action-recognition-teacher-0002/description/person-detection-action-recognition-teacher-0002.md
/usr/share/open_model_zoo/models/intel/person-detection-action-recognition-teacher-0002/description/person-detection-action-recognition-teacher-0002.png
/usr/share/open_model_zoo/models/intel/person-detection-action-recognition-teacher-0002/model.yml
/usr/share/open_model_zoo/models/intel/person-detection-action-recognition-teacher-0002/person-detection-action-recognition-teacher-0002.prototxt
/usr/share/open_model_zoo/models/intel/person-detection-raisinghand-recognition-0001/description/person-detection-raisinghand-recognition-0001.md
/usr/share/open_model_zoo/models/intel/person-detection-raisinghand-recognition-0001/description/person-detection-raisinghand-recognition-0001.png
/usr/share/open_model_zoo/models/intel/person-detection-raisinghand-recognition-0001/model.yml
/usr/share/open_model_zoo/models/intel/person-detection-raisinghand-recognition-0001/person-detection-raisinghand-recognition-0001.prototxt
/usr/share/open_model_zoo/models/intel/person-detection-retail-0002/description/person-detection-retail-0002.md
/usr/share/open_model_zoo/models/intel/person-detection-retail-0002/description/person-detection-retail-0002.png
/usr/share/open_model_zoo/models/intel/person-detection-retail-0002/model.yml
/usr/share/open_model_zoo/models/intel/person-detection-retail-0002/person-detection-retail-0002.prototxt
/usr/share/open_model_zoo/models/intel/person-detection-retail-0013/description/person-detection-retail-0013.md
/usr/share/open_model_zoo/models/intel/person-detection-retail-0013/description/person-detection-retail-0013.png
/usr/share/open_model_zoo/models/intel/person-detection-retail-0013/model.yml
/usr/share/open_model_zoo/models/intel/person-detection-retail-0013/person-detection-retail-0013.prototxt
/usr/share/open_model_zoo/models/intel/person-reidentification-retail-0031/description/person-reidentification-retail-0031.md
/usr/share/open_model_zoo/models/intel/person-reidentification-retail-0031/description/person-reidentification-retail-0031.png
/usr/share/open_model_zoo/models/intel/person-reidentification-retail-0031/model.yml
/usr/share/open_model_zoo/models/intel/person-reidentification-retail-0031/person-reidentification-retail-0031.prototxt
/usr/share/open_model_zoo/models/intel/person-reidentification-retail-0076/description/person-reidentification-retail-0076.md
/usr/share/open_model_zoo/models/intel/person-reidentification-retail-0076/description/person-reidentification-retail-0076.png
/usr/share/open_model_zoo/models/intel/person-reidentification-retail-0076/model.yml
/usr/share/open_model_zoo/models/intel/person-reidentification-retail-0076/person-reidentification-retail-0076.prototxt
/usr/share/open_model_zoo/models/intel/person-reidentification-retail-0079/description/person-reidentification-retail-0079.md
/usr/share/open_model_zoo/models/intel/person-reidentification-retail-0079/description/person-reidentification-retail-0079.png
/usr/share/open_model_zoo/models/intel/person-reidentification-retail-0079/model.yml
/usr/share/open_model_zoo/models/intel/person-reidentification-retail-0079/person-reidentification-retail-0079.prototxt
/usr/share/open_model_zoo/models/intel/person-vehicle-bike-detection-crossroad-0078/description/person-vehicle-bike-detection-crossroad-0078.md
/usr/share/open_model_zoo/models/intel/person-vehicle-bike-detection-crossroad-0078/description/person-vehicle-bike-detection-crossroad-0078.png
/usr/share/open_model_zoo/models/intel/person-vehicle-bike-detection-crossroad-0078/model.yml
/usr/share/open_model_zoo/models/intel/person-vehicle-bike-detection-crossroad-0078/person-vehicle-bike-detection-crossroad-0078.prototxt
/usr/share/open_model_zoo/models/intel/person-vehicle-bike-detection-crossroad-1016/description/person-vehicle-bike-detection-crossroad-1016.md
/usr/share/open_model_zoo/models/intel/person-vehicle-bike-detection-crossroad-1016/description/person-vehicle-bike-detection-crossroad-1016.png
/usr/share/open_model_zoo/models/intel/person-vehicle-bike-detection-crossroad-1016/model.yml
/usr/share/open_model_zoo/models/intel/resnet-50-int8-sparse-v1-tf-0001/description/resnet-50-int8-sparse-v1-tf-0001.md
/usr/share/open_model_zoo/models/intel/resnet-50-int8-sparse-v1-tf-0001/model.yml
/usr/share/open_model_zoo/models/intel/resnet-50-int8-sparse-v2-tf-0001/description/resnet-50-int8-sparse-v2-tf-0001.md
/usr/share/open_model_zoo/models/intel/resnet-50-int8-sparse-v2-tf-0001/model.yml
/usr/share/open_model_zoo/models/intel/resnet-50-int8-tf-0001/description/resnet-50-int8-tf-0001.md
/usr/share/open_model_zoo/models/intel/resnet-50-int8-tf-0001/model.yml
/usr/share/open_model_zoo/models/intel/resnet50-binary-0001/description/resnet50-binary-0001.md
/usr/share/open_model_zoo/models/intel/resnet50-binary-0001/model.yml
/usr/share/open_model_zoo/models/intel/road-segmentation-adas-0001/description/road-segmentation-adas-0001.md
/usr/share/open_model_zoo/models/intel/road-segmentation-adas-0001/description/road-segmentation-adas-0001.png
/usr/share/open_model_zoo/models/intel/road-segmentation-adas-0001/model.yml
/usr/share/open_model_zoo/models/intel/road-segmentation-adas-0001/road-segmentation-adas-0001.prototxt
/usr/share/open_model_zoo/models/intel/semantic-segmentation-adas-0001/description/semantic-segmentation-adas-0001.md
/usr/share/open_model_zoo/models/intel/semantic-segmentation-adas-0001/description/semantic-segmentation-adas-0001.png
/usr/share/open_model_zoo/models/intel/semantic-segmentation-adas-0001/model.yml
/usr/share/open_model_zoo/models/intel/semantic-segmentation-adas-0001/semantic-segmentation-adas-0001.prototxt
/usr/share/open_model_zoo/models/intel/single-image-super-resolution-1032/description/single-image-super-resolution-1032.md
/usr/share/open_model_zoo/models/intel/single-image-super-resolution-1032/description/street_480x270.png
/usr/share/open_model_zoo/models/intel/single-image-super-resolution-1032/description/x4_street_480x270.png
/usr/share/open_model_zoo/models/intel/single-image-super-resolution-1032/description/x4c_street_480x270.png
/usr/share/open_model_zoo/models/intel/single-image-super-resolution-1032/model.yml
/usr/share/open_model_zoo/models/intel/single-image-super-resolution-1033/description/single-image-super-resolution-1033.md
/usr/share/open_model_zoo/models/intel/single-image-super-resolution-1033/description/street_640x360.png
/usr/share/open_model_zoo/models/intel/single-image-super-resolution-1033/description/x3_street_640x360.png
/usr/share/open_model_zoo/models/intel/single-image-super-resolution-1033/description/x3c_street_640x360.png
/usr/share/open_model_zoo/models/intel/single-image-super-resolution-1033/model.yml
/usr/share/open_model_zoo/models/intel/text-detection-0003/description/text-detection-0003.md
/usr/share/open_model_zoo/models/intel/text-detection-0003/description/text-detection-0003.png
/usr/share/open_model_zoo/models/intel/text-detection-0003/model.yml
/usr/share/open_model_zoo/models/intel/text-detection-0004/description/text-detection-0004.md
/usr/share/open_model_zoo/models/intel/text-detection-0004/description/text-detection-0004.png
/usr/share/open_model_zoo/models/intel/text-detection-0004/model.yml
/usr/share/open_model_zoo/models/intel/text-image-super-resolution-0001/description/img.png
/usr/share/open_model_zoo/models/intel/text-image-super-resolution-0001/description/img_x3.png
/usr/share/open_model_zoo/models/intel/text-image-super-resolution-0001/description/img_x3c.png
/usr/share/open_model_zoo/models/intel/text-image-super-resolution-0001/description/text-image-super-resolution-0001.md
/usr/share/open_model_zoo/models/intel/text-image-super-resolution-0001/model.yml
/usr/share/open_model_zoo/models/intel/text-recognition-0012/description/openvino.jpg
/usr/share/open_model_zoo/models/intel/text-recognition-0012/description/text-recognition-0012.md
/usr/share/open_model_zoo/models/intel/text-recognition-0012/model.yml
/usr/share/open_model_zoo/models/intel/vehicle-attributes-recognition-barrier-0039/description/vehicle-attributes-recognition-barrier-0039-1.png
/usr/share/open_model_zoo/models/intel/vehicle-attributes-recognition-barrier-0039/description/vehicle-attributes-recognition-barrier-0039.md
/usr/share/open_model_zoo/models/intel/vehicle-attributes-recognition-barrier-0039/model.yml
/usr/share/open_model_zoo/models/intel/vehicle-attributes-recognition-barrier-0039/vehicle-attributes-recognition-barrier-0039.prototxt
/usr/share/open_model_zoo/models/intel/vehicle-detection-adas-0002/description/vehicle-detection-adas-0002.md
/usr/share/open_model_zoo/models/intel/vehicle-detection-adas-0002/description/vehicle-detection-adas-0002.png
/usr/share/open_model_zoo/models/intel/vehicle-detection-adas-0002/model.yml
/usr/share/open_model_zoo/models/intel/vehicle-detection-adas-0002/vehicle-detection-adas-0002.prototxt
/usr/share/open_model_zoo/models/intel/vehicle-detection-adas-binary-0001/description/vehicle-detection-adas-binary-0001.md
/usr/share/open_model_zoo/models/intel/vehicle-detection-adas-binary-0001/description/vehicle-detection-adas-binary-0001.png
/usr/share/open_model_zoo/models/intel/vehicle-detection-adas-binary-0001/model.yml
/usr/share/open_model_zoo/models/intel/vehicle-license-plate-detection-barrier-0106/description/vehicle-license-plate-detection-barrier-0106.jpeg
/usr/share/open_model_zoo/models/intel/vehicle-license-plate-detection-barrier-0106/description/vehicle-license-plate-detection-barrier-0106.md
/usr/share/open_model_zoo/models/intel/vehicle-license-plate-detection-barrier-0106/model.yml
/usr/share/open_model_zoo/models/public/Sphereface/Sphereface.md
/usr/share/open_model_zoo/models/public/Sphereface/model.yml
/usr/share/open_model_zoo/models/public/alexnet/alexnet.md
/usr/share/open_model_zoo/models/public/alexnet/model.yml
/usr/share/open_model_zoo/models/public/brain-tumor-segmentation-0001/brain-tumor-segmentation-0001.md
/usr/share/open_model_zoo/models/public/brain-tumor-segmentation-0001/model.yml
/usr/share/open_model_zoo/models/public/caffenet/caffenet.md
/usr/share/open_model_zoo/models/public/caffenet/model.yml
/usr/share/open_model_zoo/models/public/ctpn/ctpn.md
/usr/share/open_model_zoo/models/public/ctpn/model.yml
/usr/share/open_model_zoo/models/public/deeplabv3/deeplabv3.md
/usr/share/open_model_zoo/models/public/deeplabv3/model.yml
/usr/share/open_model_zoo/models/public/densenet-121-tf/densenet-121-tf.md
/usr/share/open_model_zoo/models/public/densenet-121-tf/model.yml
/usr/share/open_model_zoo/models/public/densenet-121/densenet-121.md
/usr/share/open_model_zoo/models/public/densenet-121/model.yml
/usr/share/open_model_zoo/models/public/densenet-161-tf/densenet-161-tf.md
/usr/share/open_model_zoo/models/public/densenet-161-tf/model.yml
/usr/share/open_model_zoo/models/public/densenet-161/densenet-161.md
/usr/share/open_model_zoo/models/public/densenet-161/model.yml
/usr/share/open_model_zoo/models/public/densenet-169-tf/densenet-169-tf.md
/usr/share/open_model_zoo/models/public/densenet-169-tf/model.yml
/usr/share/open_model_zoo/models/public/densenet-169/densenet-169.md
/usr/share/open_model_zoo/models/public/densenet-169/model.yml
/usr/share/open_model_zoo/models/public/densenet-201/densenet-201.md
/usr/share/open_model_zoo/models/public/densenet-201/model.yml
/usr/share/open_model_zoo/models/public/face-detection-retail-0044/model.yml
/usr/share/open_model_zoo/models/public/face-recognition-mobilefacenet-arcface/face-recognition-mobilefacenet-arcface.md
/usr/share/open_model_zoo/models/public/face-recognition-mobilefacenet-arcface/model.yml
/usr/share/open_model_zoo/models/public/face-recognition-resnet100-arcface/face-recognition-resnet100-arcface.md
/usr/share/open_model_zoo/models/public/face-recognition-resnet100-arcface/model.yml
/usr/share/open_model_zoo/models/public/face-recognition-resnet34-arcface/face-recognition-resnet34-arcface.md
/usr/share/open_model_zoo/models/public/face-recognition-resnet34-arcface/model.yml
/usr/share/open_model_zoo/models/public/face-recognition-resnet50-arcface/face-recognition-resnet50-arcface.md
/usr/share/open_model_zoo/models/public/face-recognition-resnet50-arcface/model.yml
/usr/share/open_model_zoo/models/public/facenet-20180408-102900/facenet-20180408-102900.md
/usr/share/open_model_zoo/models/public/facenet-20180408-102900/model.yml
/usr/share/open_model_zoo/models/public/faster_rcnn_inception_resnet_v2_atrous_coco/faster_rcnn_inception_resnet_v2_atrous_coco.md
/usr/share/open_model_zoo/models/public/faster_rcnn_inception_resnet_v2_atrous_coco/model.yml
/usr/share/open_model_zoo/models/public/faster_rcnn_inception_v2_coco/faster_rcnn_inception_v2_coco.md
/usr/share/open_model_zoo/models/public/faster_rcnn_inception_v2_coco/model.yml
/usr/share/open_model_zoo/models/public/faster_rcnn_resnet101_coco/faster_rcnn_resnet101_coco.md
/usr/share/open_model_zoo/models/public/faster_rcnn_resnet101_coco/model.yml
/usr/share/open_model_zoo/models/public/faster_rcnn_resnet50_coco/faster_rcnn_resnet50_coco.md
/usr/share/open_model_zoo/models/public/faster_rcnn_resnet50_coco/model.yml
/usr/share/open_model_zoo/models/public/googlenet-v1/googlenet-v1.md
/usr/share/open_model_zoo/models/public/googlenet-v1/model.yml
/usr/share/open_model_zoo/models/public/googlenet-v2/googlenet-v2.md
/usr/share/open_model_zoo/models/public/googlenet-v2/model.yml
/usr/share/open_model_zoo/models/public/googlenet-v3-pytorch/googlenet-v3-pytorch.md
/usr/share/open_model_zoo/models/public/googlenet-v3-pytorch/model.yml
/usr/share/open_model_zoo/models/public/googlenet-v3/googlenet-v3.md
/usr/share/open_model_zoo/models/public/googlenet-v3/model.yml
/usr/share/open_model_zoo/models/public/googlenet-v4/googlenet-v4.md
/usr/share/open_model_zoo/models/public/googlenet-v4/model.yml
/usr/share/open_model_zoo/models/public/inception-resnet-v2-tf/inception-resnet-v2-tf.md
/usr/share/open_model_zoo/models/public/inception-resnet-v2-tf/model.yml
/usr/share/open_model_zoo/models/public/inception-resnet-v2/inception-resnet-v2.md
/usr/share/open_model_zoo/models/public/inception-resnet-v2/model.yml
/usr/share/open_model_zoo/models/public/index.md
/usr/share/open_model_zoo/models/public/license-plate-recognition-barrier-0007/model.yml
/usr/share/open_model_zoo/models/public/mask_rcnn_inception_resnet_v2_atrous_coco/mask_rcnn_inception_resnet_v2_atrous_coco.md
/usr/share/open_model_zoo/models/public/mask_rcnn_inception_resnet_v2_atrous_coco/model.yml
/usr/share/open_model_zoo/models/public/mask_rcnn_inception_v2_coco/mask_rcnn_inception_v2_coco.md
/usr/share/open_model_zoo/models/public/mask_rcnn_inception_v2_coco/model.yml
/usr/share/open_model_zoo/models/public/mask_rcnn_resnet101_atrous_coco/mask_rcnn_resnet101_atrous_coco.md
/usr/share/open_model_zoo/models/public/mask_rcnn_resnet101_atrous_coco/model.yml
/usr/share/open_model_zoo/models/public/mask_rcnn_resnet50_atrous_coco/mask_rcnn_resnet50_atrous_coco.md
/usr/share/open_model_zoo/models/public/mask_rcnn_resnet50_atrous_coco/model.yml
/usr/share/open_model_zoo/models/public/mobilenet-ssd/mobilenet-ssd.md
/usr/share/open_model_zoo/models/public/mobilenet-ssd/model.yml
/usr/share/open_model_zoo/models/public/mobilenet-v1-0.25-128/mobilenet-v1-0.25-128.md
/usr/share/open_model_zoo/models/public/mobilenet-v1-0.25-128/model.yml
/usr/share/open_model_zoo/models/public/mobilenet-v1-0.50-160/mobilenet-v1-0.50-160.md
/usr/share/open_model_zoo/models/public/mobilenet-v1-0.50-160/model.yml
/usr/share/open_model_zoo/models/public/mobilenet-v1-0.50-224/mobilenet-v1-0.50-224.md
/usr/share/open_model_zoo/models/public/mobilenet-v1-0.50-224/model.yml
/usr/share/open_model_zoo/models/public/mobilenet-v1-1.0-224-tf/mobilenet-v1-1.0-224-tf.md
/usr/share/open_model_zoo/models/public/mobilenet-v1-1.0-224-tf/model.yml
/usr/share/open_model_zoo/models/public/mobilenet-v1-1.0-224/mobilenet-v1-1.0-224.md
/usr/share/open_model_zoo/models/public/mobilenet-v1-1.0-224/model.yml
/usr/share/open_model_zoo/models/public/mobilenet-v2-1.0-224/mobilenet-v2-1.0-224.md
/usr/share/open_model_zoo/models/public/mobilenet-v2-1.0-224/model.yml
/usr/share/open_model_zoo/models/public/mobilenet-v2-1.4-224/mobilenet-v2-1.4-224.md
/usr/share/open_model_zoo/models/public/mobilenet-v2-1.4-224/model.yml
/usr/share/open_model_zoo/models/public/mobilenet-v2-pytorch/mobilenet-v2-pytorch.md
/usr/share/open_model_zoo/models/public/mobilenet-v2-pytorch/model.yml
/usr/share/open_model_zoo/models/public/mobilenet-v2/mobilenet-v2.md
/usr/share/open_model_zoo/models/public/mobilenet-v2/model.yml
/usr/share/open_model_zoo/models/public/mtcnn-o/model.yml
/usr/share/open_model_zoo/models/public/mtcnn-o/mtcnn-o.md
/usr/share/open_model_zoo/models/public/mtcnn-p/model.yml
/usr/share/open_model_zoo/models/public/mtcnn-p/mtcnn-p.md
/usr/share/open_model_zoo/models/public/mtcnn-r/model.yml
/usr/share/open_model_zoo/models/public/mtcnn-r/mtcnn-r.md
/usr/share/open_model_zoo/models/public/octave-densenet-121-0.125/model.yml
/usr/share/open_model_zoo/models/public/octave-densenet-121-0.125/octave-densenet-121-0.125.md
/usr/share/open_model_zoo/models/public/octave-resnet-101-0.125/model.yml
/usr/share/open_model_zoo/models/public/octave-resnet-101-0.125/octave-resnet-101-0.125.md
/usr/share/open_model_zoo/models/public/octave-resnet-200-0.125/model.yml
/usr/share/open_model_zoo/models/public/octave-resnet-200-0.125/octave-resnet-200-0.125.md
/usr/share/open_model_zoo/models/public/octave-resnet-26-0.25/model.yml
/usr/share/open_model_zoo/models/public/octave-resnet-26-0.25/octave-resnet-26-0.25.md
/usr/share/open_model_zoo/models/public/octave-resnet-50-0.125/model.yml
/usr/share/open_model_zoo/models/public/octave-resnet-50-0.125/octave-resnet-50-0.125.md
/usr/share/open_model_zoo/models/public/octave-resnext-101-0.25/model.yml
/usr/share/open_model_zoo/models/public/octave-resnext-101-0.25/octave-resnext-101-0.25.md
/usr/share/open_model_zoo/models/public/octave-resnext-50-0.25/model.yml
/usr/share/open_model_zoo/models/public/octave-resnext-50-0.25/octave-resnext-50-0.25.md
/usr/share/open_model_zoo/models/public/octave-se-resnet-50-0.125/model.yml
/usr/share/open_model_zoo/models/public/octave-se-resnet-50-0.125/octave-se-resnet-50-0.125.md
/usr/share/open_model_zoo/models/public/resnet-101/model.yml
/usr/share/open_model_zoo/models/public/resnet-101/resnet-101.md
/usr/share/open_model_zoo/models/public/resnet-152/model.yml
/usr/share/open_model_zoo/models/public/resnet-152/resnet-152.md
/usr/share/open_model_zoo/models/public/resnet-50-pytorch/model.yml
/usr/share/open_model_zoo/models/public/resnet-50-pytorch/resnet-50-pytorch.md
/usr/share/open_model_zoo/models/public/resnet-50/model.yml
/usr/share/open_model_zoo/models/public/resnet-50/resnet-50.md
/usr/share/open_model_zoo/models/public/se-inception/model.yml
/usr/share/open_model_zoo/models/public/se-inception/se-inception.md
/usr/share/open_model_zoo/models/public/se-resnet-101/model.yml
/usr/share/open_model_zoo/models/public/se-resnet-101/se-resnet-101.md
/usr/share/open_model_zoo/models/public/se-resnet-152/model.yml
/usr/share/open_model_zoo/models/public/se-resnet-152/se-resnet-152.md
/usr/share/open_model_zoo/models/public/se-resnet-50/model.yml
/usr/share/open_model_zoo/models/public/se-resnet-50/se-resnet-50.md
/usr/share/open_model_zoo/models/public/se-resnext-101/model.yml
/usr/share/open_model_zoo/models/public/se-resnext-101/se-resnext-101.md
/usr/share/open_model_zoo/models/public/se-resnext-50/model.yml
/usr/share/open_model_zoo/models/public/se-resnext-50/se-resnext-50.md
/usr/share/open_model_zoo/models/public/squeezenet1.0/model.yml
/usr/share/open_model_zoo/models/public/squeezenet1.0/squeezenet1.0.md
/usr/share/open_model_zoo/models/public/squeezenet1.1/model.yml
/usr/share/open_model_zoo/models/public/squeezenet1.1/squeezenet1.1.md
/usr/share/open_model_zoo/models/public/ssd300/model.yml
/usr/share/open_model_zoo/models/public/ssd300/ssd300.md
/usr/share/open_model_zoo/models/public/ssd512/model.yml
/usr/share/open_model_zoo/models/public/ssd512/ssd512.md
/usr/share/open_model_zoo/models/public/ssd_mobilenet_v1_coco/model.yml
/usr/share/open_model_zoo/models/public/ssd_mobilenet_v1_coco/ssd_mobilenet_v1_coco.md
/usr/share/open_model_zoo/models/public/ssd_mobilenet_v1_fpn_coco/model.yml
/usr/share/open_model_zoo/models/public/ssd_mobilenet_v1_fpn_coco/ssd_mobilenet_v1_fpn_coco.md
/usr/share/open_model_zoo/models/public/ssd_mobilenet_v2_coco/model.yml
/usr/share/open_model_zoo/models/public/ssd_mobilenet_v2_coco/ssd_mobilenet_v2_coco.md
/usr/share/open_model_zoo/models/public/ssdlite_mobilenet_v2/model.yml
/usr/share/open_model_zoo/models/public/ssdlite_mobilenet_v2/ssdlite_mobilenet_v2.md
/usr/share/open_model_zoo/models/public/vgg16/model.yml
/usr/share/open_model_zoo/models/public/vgg16/vgg16.md
/usr/share/open_model_zoo/models/public/vgg19/model.yml
/usr/share/open_model_zoo/models/public/vgg19/vgg19.md
/usr/share/open_model_zoo/tools/accuracy_checker/.pylintrc
/usr/share/open_model_zoo/tools/accuracy_checker/README.md
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/__init__.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/adapters/README.md
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/adapters/__init__.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/adapters/action_recognition.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/adapters/adapter.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/adapters/attributes_recognition.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/adapters/classification.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/adapters/detection.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/adapters/dummy_adapters.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/adapters/hit_ratio.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/adapters/image_processing.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/adapters/mask_rcnn.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/adapters/nlp.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/adapters/pose_estimation.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/adapters/reidentification.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/adapters/segmentation.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/adapters/text_detection.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/annotation_converters/README.md
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/annotation_converters/__init__.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/annotation_converters/_reid_common.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/annotation_converters/brats.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/annotation_converters/camvid.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/annotation_converters/cifar10.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/annotation_converters/cityscapes.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/annotation_converters/common_semantic_segmentation.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/annotation_converters/convert.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/annotation_converters/cvat_age_gender_recognition.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/annotation_converters/cvat_attributes_recognition.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/annotation_converters/cvat_facial_landmarks.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/annotation_converters/cvat_human_pose.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/annotation_converters/cvat_multilabel_recognition.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/annotation_converters/cvat_object_detection.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/annotation_converters/cvat_person_detection_action_recognition.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/annotation_converters/cvat_text_recognition.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/annotation_converters/detection_opencv_storage.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/annotation_converters/format_converter.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/annotation_converters/icdar.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/annotation_converters/image_retrieval.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/annotation_converters/imagenet.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/annotation_converters/lfw.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/annotation_converters/lpr.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/annotation_converters/market1501.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/annotation_converters/mars.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/annotation_converters/mnist.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/annotation_converters/ms_coco.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/annotation_converters/ncf_converter.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/annotation_converters/pascal_voc.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/annotation_converters/sample_converter.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/annotation_converters/super_resolution_converter.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/annotation_converters/vgg_face_regression.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/annotation_converters/wider.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/annotation_converters/wmt.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/config/__init__.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/config/config_reader.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/config/config_validator.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/data_analyzer/__init__.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/data_analyzer/base_data_analyzer.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/data_analyzer/classification_analyzer.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/data_analyzer/container_analyzer.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/data_analyzer/detection_analyzer.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/data_analyzer/multi_label_recognition_analyzer.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/data_analyzer/regression_analyzer.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/data_readers/README.md
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/data_readers/__init__.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/data_readers/data_reader.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/dataset.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/dependency.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/evaluators/__init__.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/evaluators/model_evaluator.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/evaluators/pipeline_evaluator.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/evaluators/quantization_model_evaluator.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/launcher/__init__.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/launcher/caffe_installation_readme.md
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/launcher/caffe_launcher.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/launcher/caffe_launcher_readme.md
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/launcher/dlsdk_launcher.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/launcher/dlsdk_launcher_readme.md
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/launcher/dummy_launcher.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/launcher/input_feeder.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/launcher/launcher.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/launcher/loaders/__init__.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/launcher/loaders/loader.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/launcher/loaders/pickle_loader.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/launcher/loaders/xml_loader.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/launcher/model_conversion.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/launcher/mxnet_launcher.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/launcher/mxnet_launcher_readme.md
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/launcher/onnx_launcher.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/launcher/onnx_runtime_launcher_readme.md
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/launcher/opencv_launcher.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/launcher/opencv_launcher_readme.md
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/launcher/tf_launcher.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/launcher/tf_launcher_readme.md
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/launcher/tf_lite_launcher.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/launcher/tf_lite_launcher_readme.md
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/logging.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/main.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/metrics/README.md
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/metrics/__init__.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/metrics/average_meter.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/metrics/character_recognition.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/metrics/classification.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/metrics/coco_metrics.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/metrics/coco_orig_metrics.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/metrics/detection.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/metrics/hit_ratio.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/metrics/machine_translation.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/metrics/metric.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/metrics/metric_executor.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/metrics/multilabel_recognition.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/metrics/overlap.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/metrics/regression.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/metrics/reid.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/metrics/semantic_segmentation.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/metrics/text_detection.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/pipeline_connectors/__init__.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/pipeline_connectors/connectors.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/postprocessor/README.md
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/postprocessor/__init__.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/postprocessor/cast_to_int.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/postprocessor/clip_boxes.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/postprocessor/clip_points.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/postprocessor/clip_segmentation_mask.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/postprocessor/correct_yolo_v2_boxes.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/postprocessor/crop_segmentation_mask.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/postprocessor/encode_segmentation_mask.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/postprocessor/extend_segmentation_mask.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/postprocessor/faster_rcnn_postprocessing_resize.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/postprocessor/filter.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/postprocessor/nms.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/postprocessor/normalize_boxes.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/postprocessor/normalize_landmarks_points.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/postprocessor/postprocessing_executor.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/postprocessor/postprocessor.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/postprocessor/resample_segmentation_prediction.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/postprocessor/resize_prediction_boxes.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/postprocessor/resize_segmentation_mask.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/postprocessor/zoom_segmentation_mask.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/preprocessor/README.md
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/preprocessor/__init__.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/preprocessor/color_spece_conversion.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/preprocessor/geometric_transformations.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/preprocessor/nlp_preprocessors.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/preprocessor/normalization.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/preprocessor/preprocessing_executor.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/preprocessor/preprocessor.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/presenters.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/progress_reporters.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/representation/__init__.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/representation/base_representation.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/representation/character_recognition_representation.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/representation/classification_representation.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/representation/detection_representation.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/representation/hit_ratio_representation.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/representation/multilabel_recognition.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/representation/nlp_representation.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/representation/pose_estimation_representation.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/representation/regression_representation.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/representation/reid_representation.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/representation/representaton_container.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/representation/segmentation_representation.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/representation/super_resolution_representation.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/representation/text_detection_representation.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/serialize_parameters.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/statistics_collector/__init__.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/statistics_collector/statistics_collector.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/topology_types.py
/usr/share/open_model_zoo/tools/accuracy_checker/accuracy_checker/utils.py
/usr/share/open_model_zoo/tools/accuracy_checker/configs/age-gender-recognition-retail-0013.yml
/usr/share/open_model_zoo/tools/accuracy_checker/configs/alexnet.yml
/usr/share/open_model_zoo/tools/accuracy_checker/configs/caffenet.yml
/usr/share/open_model_zoo/tools/accuracy_checker/configs/deeplabv3.yml
/usr/share/open_model_zoo/tools/accuracy_checker/configs/densenet-121-tf.yml
/usr/share/open_model_zoo/tools/accuracy_checker/configs/densenet-121.yml
/usr/share/open_model_zoo/tools/accuracy_checker/configs/densenet-161-tf.yml
/usr/share/open_model_zoo/tools/accuracy_checker/configs/densenet-161.yml
/usr/share/open_model_zoo/tools/accuracy_checker/configs/densenet-169-tf.yml
/usr/share/open_model_zoo/tools/accuracy_checker/configs/densenet-169.yml
/usr/share/open_model_zoo/tools/accuracy_checker/configs/densenet-201.yml
/usr/share/open_model_zoo/tools/accuracy_checker/configs/emotions-recognition-retail-0003.yml
/usr/share/open_model_zoo/tools/accuracy_checker/configs/face-detection-adas-0001.yml
/usr/share/open_model_zoo/tools/accuracy_checker/configs/face-detection-adas-binary-0001.yml
/usr/share/open_model_zoo/tools/accuracy_checker/configs/face-detection-retail-0004.yml
/usr/share/open_model_zoo/tools/accuracy_checker/configs/face-detection-retail-0005.yml
/usr/share/open_model_zoo/tools/accuracy_checker/configs/face-detection-retail-0044.yml
/usr/share/open_model_zoo/tools/accuracy_checker/configs/face-recognition-mobilefacenet-arcface.yml
/usr/share/open_model_zoo/tools/accuracy_checker/configs/face-recognition-resnet100-arcface.yml
/usr/share/open_model_zoo/tools/accuracy_checker/configs/face-recognition-resnet34-arcface.yml
/usr/share/open_model_zoo/tools/accuracy_checker/configs/face-recognition-resnet50-arcface.yml
/usr/share/open_model_zoo/tools/accuracy_checker/configs/face-reidentification-retail-0095.yml
/usr/share/open_model_zoo/tools/accuracy_checker/configs/facial-landmarks-35-adas-0002.yml
/usr/share/open_model_zoo/tools/accuracy_checker/configs/faster_rcnn_inception_resnet_v2_atrous_coco.yml
/usr/share/open_model_zoo/tools/accuracy_checker/configs/faster_rcnn_inception_v2_coco.yml
/usr/share/open_model_zoo/tools/accuracy_checker/configs/faster_rcnn_resnet101_coco.yml
/usr/share/open_model_zoo/tools/accuracy_checker/configs/faster_rcnn_resnet50_coco.yml
/usr/share/open_model_zoo/tools/accuracy_checker/configs/googlenet-v1.yml
/usr/share/open_model_zoo/tools/accuracy_checker/configs/googlenet-v2.yml
/usr/share/open_model_zoo/tools/accuracy_checker/configs/googlenet-v3-pytorch.yml
/usr/share/open_model_zoo/tools/accuracy_checker/configs/googlenet-v3.yml
/usr/share/open_model_zoo/tools/accuracy_checker/configs/googlenet-v4.yml
/usr/share/open_model_zoo/tools/accuracy_checker/configs/human-pose-estimation-0001.yml
/usr/share/open_model_zoo/tools/accuracy_checker/configs/inception-resnet-v2-tf.yml
/usr/share/open_model_zoo/tools/accuracy_checker/configs/inception-resnet-v2.yml
/usr/share/open_model_zoo/tools/accuracy_checker/configs/inceptionv3-int8-sparse-v1-tf-0001.yml
/usr/share/open_model_zoo/tools/accuracy_checker/configs/inceptionv3-int8-sparse-v2-tf-0001.yml
/usr/share/open_model_zoo/tools/accuracy_checker/configs/inceptionv3-int8-tf-0001.yml
/usr/share/open_model_zoo/tools/accuracy_checker/configs/instance-segmentation-security-0010.yml
/usr/share/open_model_zoo/tools/accuracy_checker/configs/instance-segmentation-security-0050.yml
/usr/share/open_model_zoo/tools/accuracy_checker/configs/instance-segmentation-security-0083.yml
/usr/share/open_model_zoo/tools/accuracy_checker/configs/landmarks-regression-retail-0009.yml
/usr/share/open_model_zoo/tools/accuracy_checker/configs/license-plate-recognition-barrier-0001.yml
/usr/share/open_model_zoo/tools/accuracy_checker/configs/license-plate-recognition-barrier-0007.yml
/usr/share/open_model_zoo/tools/accuracy_checker/configs/mask_rcnn_inception_resnet_v2_atrous_coco.yml
/usr/share/open_model_zoo/tools/accuracy_checker/configs/mask_rcnn_inception_v2_coco.yml
/usr/share/open_model_zoo/tools/accuracy_checker/configs/mask_rcnn_resnet101_atrous_coco.yml
/usr/share/open_model_zoo/tools/accuracy_checker/configs/mask_rcnn_resnet50_atrous_coco.yml
/usr/share/open_model_zoo/tools/accuracy_checker/configs/mobilenet-ssd.yml
/usr/share/open_model_zoo/tools/accuracy_checker/configs/mobilenet-v1-0.25-128.yml
/usr/share/open_model_zoo/tools/accuracy_checker/configs/mobilenet-v1-0.50-160.yml
/usr/share/open_model_zoo/tools/accuracy_checker/configs/mobilenet-v1-0.50-224.yml
/usr/share/open_model_zoo/tools/accuracy_checker/configs/mobilenet-v1-1.0-224-tf.yml
/usr/share/open_model_zoo/tools/accuracy_checker/configs/mobilenet-v1-1.0-224.yml
/usr/share/open_model_zoo/tools/accuracy_checker/configs/mobilenet-v2-1.0-224.yml
/usr/share/open_model_zoo/tools/accuracy_checker/configs/mobilenet-v2-1.4-224.yml
/usr/share/open_model_zoo/tools/accuracy_checker/configs/mobilenet-v2-pytorch.yml
/usr/share/open_model_zoo/tools/accuracy_checker/configs/mobilenet-v2.yml
/usr/share/open_model_zoo/tools/accuracy_checker/configs/mobilenetv2-int8-sparse-v1-tf-0001.yml
/usr/share/open_model_zoo/tools/accuracy_checker/configs/mobilenetv2-int8-sparse-v2-tf-0001.yml
/usr/share/open_model_zoo/tools/accuracy_checker/configs/mobilenetv2-int8-tf-0001.yml
/usr/share/open_model_zoo/tools/accuracy_checker/configs/octave-densenet-121-0.125.yml
/usr/share/open_model_zoo/tools/accuracy_checker/configs/octave-resnet-101-0.125.yml
/usr/share/open_model_zoo/tools/accuracy_checker/configs/octave-resnet-200-0.125.yml
/usr/share/open_model_zoo/tools/accuracy_checker/configs/octave-resnet-26-0.25.yml
/usr/share/open_model_zoo/tools/accuracy_checker/configs/octave-resnet-50-0.125.yml
/usr/share/open_model_zoo/tools/accuracy_checker/configs/octave-resnext-101-0.25.yml
/usr/share/open_model_zoo/tools/accuracy_checker/configs/octave-resnext-50-0.25.yml
/usr/share/open_model_zoo/tools/accuracy_checker/configs/octave-se-resnet-50-0.125.yml
/usr/share/open_model_zoo/tools/accuracy_checker/configs/pedestrian-and-vehicle-detector-adas-0001.yml
/usr/share/open_model_zoo/tools/accuracy_checker/configs/pedestrian-detection-adas-0002.yml
/usr/share/open_model_zoo/tools/accuracy_checker/configs/pedestrian-detection-adas-binary-0001.yml
/usr/share/open_model_zoo/tools/accuracy_checker/configs/person-attributes-recognition-crossroad-0230.yml
/usr/share/open_model_zoo/tools/accuracy_checker/configs/person-detection-action-recognition-0005.yml
/usr/share/open_model_zoo/tools/accuracy_checker/configs/person-detection-action-recognition-0006.yml
/usr/share/open_model_zoo/tools/accuracy_checker/configs/person-detection-action-recognition-teacher-0002.yml
/usr/share/open_model_zoo/tools/accuracy_checker/configs/person-detection-raisinghand-recognition-0001.yml
/usr/share/open_model_zoo/tools/accuracy_checker/configs/person-detection-retail-0002.yml
/usr/share/open_model_zoo/tools/accuracy_checker/configs/person-detection-retail-0013.yml
/usr/share/open_model_zoo/tools/accuracy_checker/configs/person-reidentification-retail-0031.yml
/usr/share/open_model_zoo/tools/accuracy_checker/configs/person-reidentification-retail-0076.yml
/usr/share/open_model_zoo/tools/accuracy_checker/configs/person-reidentification-retail-0079.yml
/usr/share/open_model_zoo/tools/accuracy_checker/configs/person-vehicle-bike-detection-crossroad-0078.yml
/usr/share/open_model_zoo/tools/accuracy_checker/configs/person-vehicle-bike-detection-crossroad-1016.yml
/usr/share/open_model_zoo/tools/accuracy_checker/configs/resnet-101.yml
/usr/share/open_model_zoo/tools/accuracy_checker/configs/resnet-152.yml
/usr/share/open_model_zoo/tools/accuracy_checker/configs/resnet-50-int8-sparse-v1-tf-0001.yml
/usr/share/open_model_zoo/tools/accuracy_checker/configs/resnet-50-int8-sparse-v2-tf-0001.yml
/usr/share/open_model_zoo/tools/accuracy_checker/configs/resnet-50-int8-tf-0001.yml
/usr/share/open_model_zoo/tools/accuracy_checker/configs/resnet-50-pytorch.yml
/usr/share/open_model_zoo/tools/accuracy_checker/configs/resnet-50.yml
/usr/share/open_model_zoo/tools/accuracy_checker/configs/resnet50-binary-0001.yml
/usr/share/open_model_zoo/tools/accuracy_checker/configs/se-inception.yml
/usr/share/open_model_zoo/tools/accuracy_checker/configs/se-resnet-101.yml
/usr/share/open_model_zoo/tools/accuracy_checker/configs/se-resnet-152.yml
/usr/share/open_model_zoo/tools/accuracy_checker/configs/se-resnet-50.yml
/usr/share/open_model_zoo/tools/accuracy_checker/configs/se-resnext-101.yml
/usr/share/open_model_zoo/tools/accuracy_checker/configs/se-resnext-50.yml
/usr/share/open_model_zoo/tools/accuracy_checker/configs/squeezenet1.0.yml
/usr/share/open_model_zoo/tools/accuracy_checker/configs/squeezenet1.1.yml
/usr/share/open_model_zoo/tools/accuracy_checker/configs/ssd300.yml
/usr/share/open_model_zoo/tools/accuracy_checker/configs/ssd512.yml
/usr/share/open_model_zoo/tools/accuracy_checker/configs/ssd_mobilenet_v1_coco.yml
/usr/share/open_model_zoo/tools/accuracy_checker/configs/ssd_mobilenet_v1_fpn_coco.yml
/usr/share/open_model_zoo/tools/accuracy_checker/configs/ssd_mobilenet_v2_coco.yml
/usr/share/open_model_zoo/tools/accuracy_checker/configs/ssdlite_mobilenet_v2.yml
/usr/share/open_model_zoo/tools/accuracy_checker/configs/text-detection-0003.yml
/usr/share/open_model_zoo/tools/accuracy_checker/configs/text-detection-0004.yml
/usr/share/open_model_zoo/tools/accuracy_checker/configs/text-recognition-0012.yml
/usr/share/open_model_zoo/tools/accuracy_checker/configs/vehicle-attributes-recognition-barrier-0039.yml
/usr/share/open_model_zoo/tools/accuracy_checker/configs/vehicle-detection-adas-0002.yml
/usr/share/open_model_zoo/tools/accuracy_checker/configs/vehicle-detection-adas-binary-0001.yml
/usr/share/open_model_zoo/tools/accuracy_checker/configs/vehicle-license-plate-detection-barrier-0106.yml
/usr/share/open_model_zoo/tools/accuracy_checker/configs/vgg16.yml
/usr/share/open_model_zoo/tools/accuracy_checker/configs/vgg19.yml
/usr/share/open_model_zoo/tools/accuracy_checker/data/test_data/1.jpg
/usr/share/open_model_zoo/tools/accuracy_checker/data/test_models/SampLeNet.bin
/usr/share/open_model_zoo/tools/accuracy_checker/data/test_models/SampLeNet.caffemodel
/usr/share/open_model_zoo/tools/accuracy_checker/data/test_models/SampLeNet.prototxt
/usr/share/open_model_zoo/tools/accuracy_checker/data/test_models/SampLeNet.xml
/usr/share/open_model_zoo/tools/accuracy_checker/data/test_models/samplenet-0000.params
/usr/share/open_model_zoo/tools/accuracy_checker/data/test_models/samplenet-symbol.json
/usr/share/open_model_zoo/tools/accuracy_checker/data/test_models/samplenet.onnx
/usr/share/open_model_zoo/tools/accuracy_checker/data/test_models/samplenet.pb
/usr/share/open_model_zoo/tools/accuracy_checker/dataset_definitions.yml
/usr/share/open_model_zoo/tools/accuracy_checker/pylint_checkers.py
/usr/share/open_model_zoo/tools/accuracy_checker/sample/README.md
/usr/share/open_model_zoo/tools/accuracy_checker/sample/opencv_sample_config.yml
/usr/share/open_model_zoo/tools/accuracy_checker/sample/sample_config.yml
/usr/share/open_model_zoo/tools/accuracy_checker/setup.cfg
/usr/share/open_model_zoo/tools/accuracy_checker/setup.py
/usr/share/open_model_zoo/tools/accuracy_checker/tests/__init__.py
/usr/share/open_model_zoo/tools/accuracy_checker/tests/common.py
/usr/share/open_model_zoo/tools/accuracy_checker/tests/conftest.py
/usr/share/open_model_zoo/tools/accuracy_checker/tests/test_adapters.py
/usr/share/open_model_zoo/tools/accuracy_checker/tests/test_caffe_launcher.py
/usr/share/open_model_zoo/tools/accuracy_checker/tests/test_config_reader.py
/usr/share/open_model_zoo/tools/accuracy_checker/tests/test_config_validator.py
/usr/share/open_model_zoo/tools/accuracy_checker/tests/test_dataset.py
/usr/share/open_model_zoo/tools/accuracy_checker/tests/test_dependency.py
/usr/share/open_model_zoo/tools/accuracy_checker/tests/test_detection_metrics.py
/usr/share/open_model_zoo/tools/accuracy_checker/tests/test_dlsdk_launcher.py
/usr/share/open_model_zoo/tools/accuracy_checker/tests/test_input_feeder.py
/usr/share/open_model_zoo/tools/accuracy_checker/tests/test_metric_evaluator.py
/usr/share/open_model_zoo/tools/accuracy_checker/tests/test_model_conversion.py
/usr/share/open_model_zoo/tools/accuracy_checker/tests/test_model_evaluator.py
/usr/share/open_model_zoo/tools/accuracy_checker/tests/test_mxnet_launcher.py
/usr/share/open_model_zoo/tools/accuracy_checker/tests/test_onnx_launcher.py
/usr/share/open_model_zoo/tools/accuracy_checker/tests/test_opencv_launcher.py
/usr/share/open_model_zoo/tools/accuracy_checker/tests/test_parameters.py
/usr/share/open_model_zoo/tools/accuracy_checker/tests/test_postprocessor.py
/usr/share/open_model_zoo/tools/accuracy_checker/tests/test_preprocessor.py
/usr/share/open_model_zoo/tools/accuracy_checker/tests/test_presenter.py
/usr/share/open_model_zoo/tools/accuracy_checker/tests/test_regression_metrics.py
/usr/share/open_model_zoo/tools/accuracy_checker/tests/test_reid_metrics.py
/usr/share/open_model_zoo/tools/accuracy_checker/tests/test_segmentation_metrics.py
/usr/share/open_model_zoo/tools/accuracy_checker/tests/test_tf_launcher.py
/usr/share/open_model_zoo/tools/accuracy_checker/tests/test_utils.py
/usr/share/open_model_zoo/tools/downloader/README.md
/usr/share/open_model_zoo/tools/downloader/common.py
/usr/share/open_model_zoo/tools/downloader/converter.py
/usr/share/open_model_zoo/tools/downloader/downloader.py
/usr/share/open_model_zoo/tools/downloader/info_dumper.py
/usr/share/open_model_zoo/tools/downloader/license.txt
/usr/share/open_model_zoo/tools/downloader/pytorch_to_onnx.py
/usr/share/open_model_zoo/tools/downloader/requirements-pytorch.in
/usr/share/open_model_zoo/tools/downloader/requirements.in
/usr/share/open_model_zoo/tools/downloader/tests/representative-models.lst

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/open_model_zoo/7df059597099bb7dcf25d2a9aedfaf4465f72d8d
/usr/share/package-licenses/open_model_zoo/b2d4ab17f1b8ef9e0646ba932dce81efe3b852ab
/usr/share/package-licenses/open_model_zoo/b3e1bac179417a8acb7aca742178befb9b18950d
