#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : open_model_zoo
Version  : 2019.r1
Release  : 2
URL      : https://github.com/opencv/open_model_zoo/archive/2019_R1.tar.gz
Source0  : https://github.com/opencv/open_model_zoo/archive/2019_R1.tar.gz
Summary  : @PACKAGE_DESCRIPTION@
Group    : Development/Tools
License  : Apache-2.0 BSD-3-Clause
Requires: open_model_zoo-data = %{version}-%{release}
Requires: open_model_zoo-license = %{version}-%{release}
Requires: Pillow
Requires: numpy
Requires: scipy
BuildRequires : Pillow
BuildRequires : buildreq-cmake
BuildRequires : numpy
BuildRequires : scipy

%description
# [OpenVINO™ Toolkit](https://01.org/openvinotoolkit) - Open Model Zoo repository
[![Build Status](http://134.191.240.124/buildStatus/icon?job=omz/2018/trigger)](http://134.191.240.124/job/omz/job/2018/job/trigger/)
[![Stable release](https://img.shields.io/badge/version-2018.R5-green.svg)](https://github.com/opencv/open_model_zoo/releases/tag/2018_R5)
[![Gitter chat](https://badges.gitter.im/gitterHQ/gitter.png)](https://gitter.im/open_model_zoo/community)
[![Apache License Version 2.0](https://img.shields.io/badge/license-Apache_2.0-green.svg)](LICENSE)

%package data
Summary: data components for the open_model_zoo package.
Group: Data

%description data
data components for the open_model_zoo package.


%package license
Summary: license components for the open_model_zoo package.
Group: Default

%description license
license components for the open_model_zoo package.


%prep
%setup -q -n open_model_zoo-2019_R1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1568077954
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
make  %{?_smp_mflags} || :


%install
export SOURCE_DATE_EPOCH=1568077954
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/open_model_zoo
cp LICENSE %{buildroot}/usr/share/package-licenses/open_model_zoo/LICENSE
cp demos/thirdparty/gflags/COPYING.txt %{buildroot}/usr/share/package-licenses/open_model_zoo/demos_thirdparty_gflags_COPYING.txt
cp intel_models/LICENSE %{buildroot}/usr/share/package-licenses/open_model_zoo/intel_models_LICENSE
cp model_downloader/license.txt %{buildroot}/usr/share/package-licenses/open_model_zoo/model_downloader_license.txt
:
## install_append content
mkdir -p %{buildroot}/usr/share/open_model_zoo
cp -ar intel_models %{buildroot}/usr/share/open_model_zoo/
cp -ar model_downloader %{buildroot}/usr/share/open_model_zoo/
## install_append end

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/open_model_zoo/intel_models/LICENSE
/usr/share/open_model_zoo/intel_models/action-recognition-0001-decoder/description/action-recognition-0001-decoder.md
/usr/share/open_model_zoo/intel_models/action-recognition-0001-decoder/description/demo.png
/usr/share/open_model_zoo/intel_models/action-recognition-0001-encoder/description/action-recognition-0001-encoder.md
/usr/share/open_model_zoo/intel_models/action-recognition-0001-encoder/description/demo.png
/usr/share/open_model_zoo/intel_models/age-gender-recognition-retail-0013/age-gender-recognition-retail-0013.prototxt
/usr/share/open_model_zoo/intel_models/age-gender-recognition-retail-0013/description/age-gender-recognition-retail-0001.jpg
/usr/share/open_model_zoo/intel_models/age-gender-recognition-retail-0013/description/age-gender-recognition-retail-0002.png
/usr/share/open_model_zoo/intel_models/age-gender-recognition-retail-0013/description/age-gender-recognition-retail-0003.png
/usr/share/open_model_zoo/intel_models/age-gender-recognition-retail-0013/description/age-gender-recognition-retail-0013.md
/usr/share/open_model_zoo/intel_models/driver-action-recognition-adas-0002-decoder/description/action-recognition-kelly.png
/usr/share/open_model_zoo/intel_models/driver-action-recognition-adas-0002-decoder/description/driver-action-recognition-adas-0002-decoder.md
/usr/share/open_model_zoo/intel_models/driver-action-recognition-adas-0002-encoder/description/action-recognition-kelly.png
/usr/share/open_model_zoo/intel_models/driver-action-recognition-adas-0002-encoder/description/driver-action-recognition-adas-0002-encoder.md
/usr/share/open_model_zoo/intel_models/emotions-recognition-retail-0003/description/emotions-recognition-retail-0003.jpg
/usr/share/open_model_zoo/intel_models/emotions-recognition-retail-0003/description/emotions-recognition-retail-0003.md
/usr/share/open_model_zoo/intel_models/emotions-recognition-retail-0003/emotions-recognition-retail-0003.prototxt
/usr/share/open_model_zoo/intel_models/face-detection-adas-0001/description/face-detection-adas-0001.md
/usr/share/open_model_zoo/intel_models/face-detection-adas-0001/description/face-detection-adas-0001.png
/usr/share/open_model_zoo/intel_models/face-detection-adas-0001/face-detection-adas-0001.prototxt
/usr/share/open_model_zoo/intel_models/face-detection-adas-binary-0001/description/face-detection-adas-binary-0001.md
/usr/share/open_model_zoo/intel_models/face-detection-adas-binary-0001/description/face-detection-adas-binary-0001.png
/usr/share/open_model_zoo/intel_models/face-detection-retail-0004/description/face-detection-retail-0001.png
/usr/share/open_model_zoo/intel_models/face-detection-retail-0004/description/face-detection-retail-0004.md
/usr/share/open_model_zoo/intel_models/face-detection-retail-0004/face-detection-retail-0004.prototxt
/usr/share/open_model_zoo/intel_models/face-person-detection-retail-0002/description/face-person-detection-retail-0002.md
/usr/share/open_model_zoo/intel_models/face-person-detection-retail-0002/description/face-person-detection-retail-0002.png
/usr/share/open_model_zoo/intel_models/face-person-detection-retail-0002/face-person-detection-retail-0002.prototxt
/usr/share/open_model_zoo/intel_models/face-reidentification-retail-0095/description/face-reidentification-retail-0095.md
/usr/share/open_model_zoo/intel_models/face-reidentification-retail-0095/description/face-reidentification-retail-0095.png
/usr/share/open_model_zoo/intel_models/facial-landmarks-35-adas-0002/description/error_formula.png
/usr/share/open_model_zoo/intel_models/facial-landmarks-35-adas-0002/description/facial-landmarks-35-adas-0002.md
/usr/share/open_model_zoo/intel_models/facial-landmarks-35-adas-0002/description/landmarks_illustration.png
/usr/share/open_model_zoo/intel_models/facial-landmarks-35-adas-0002/facial-landmarks-35-adas-0002.prototxt
/usr/share/open_model_zoo/intel_models/gaze-estimation-adas-0002/description/gaze-estimation-adas-0002.md
/usr/share/open_model_zoo/intel_models/gaze-estimation-adas-0002/description/ill_for_gaze.png
/usr/share/open_model_zoo/intel_models/handwritten-score-recognition-0001/description/handwritten-score-recognition-0001.md
/usr/share/open_model_zoo/intel_models/handwritten-score-recognition-0001/description/shot_25.png
/usr/share/open_model_zoo/intel_models/head-pose-estimation-adas-0001/description/head-pose-estimation-adas-0001.md
/usr/share/open_model_zoo/intel_models/head-pose-estimation-adas-0001/description/head-pose-estimation-adas-0001.png
/usr/share/open_model_zoo/intel_models/head-pose-estimation-adas-0001/head-pose-estimation-adas-0001.prototxt
/usr/share/open_model_zoo/intel_models/human-pose-estimation-0001/description/human-pose-estimation-0001.md
/usr/share/open_model_zoo/intel_models/human-pose-estimation-0001/description/human-pose-estimation-0001.png
/usr/share/open_model_zoo/intel_models/human-pose-estimation-0001/human-pose-estimation-0001.prototxt
/usr/share/open_model_zoo/intel_models/index.md
/usr/share/open_model_zoo/intel_models/instance-segmentation-security-0033/description/instance-segmentation-security-0033.md
/usr/share/open_model_zoo/intel_models/instance-segmentation-security-0033/description/instance-segmentation-security-0033.png
/usr/share/open_model_zoo/intel_models/instance-segmentation-security-0049/description/instance-segmentation-security-0049.md
/usr/share/open_model_zoo/intel_models/instance-segmentation-security-0049/description/instance-segmentation-security-0049.png
/usr/share/open_model_zoo/intel_models/intel_logo.png
/usr/share/open_model_zoo/intel_models/intel_styles.css
/usr/share/open_model_zoo/intel_models/landmarks-regression-retail-0009/description/landmarks-regression-retail-0009.md
/usr/share/open_model_zoo/intel_models/landmarks-regression-retail-0009/description/landmarks-regression-retail-0009.png
/usr/share/open_model_zoo/intel_models/landmarks-regression-retail-0009/description/normed_error.png
/usr/share/open_model_zoo/intel_models/license-plate-recognition-barrier-0001/description/license-plate-recognition-barrier-0001.md
/usr/share/open_model_zoo/intel_models/license-plate-recognition-barrier-0001/description/license-plate-recognition-barrier-0001.png
/usr/share/open_model_zoo/intel_models/license-plate-recognition-barrier-0001/license-plate-recognition-barrier-0001.prototxt
/usr/share/open_model_zoo/intel_models/pedestrian-and-vehicle-detector-adas-0001/description/pedestrian-and-vehicle-detector-adas-0001.md
/usr/share/open_model_zoo/intel_models/pedestrian-and-vehicle-detector-adas-0001/description/pedestrian-and-vehicle-detector-adas-0001.png
/usr/share/open_model_zoo/intel_models/pedestrian-and-vehicle-detector-adas-0001/pedestrian-and-vehicle-detector-adas-0001.prototxt
/usr/share/open_model_zoo/intel_models/pedestrian-detection-adas-0002/description/pedestrian-detection-adas-0002.md
/usr/share/open_model_zoo/intel_models/pedestrian-detection-adas-0002/description/pedestrian-detection-adas-0002.png
/usr/share/open_model_zoo/intel_models/pedestrian-detection-adas-0002/pedestrian-detection-adas-0002.prototxt
/usr/share/open_model_zoo/intel_models/pedestrian-detection-adas-binary-0001/description/pedestrian-detection-adas-binary-0001.md
/usr/share/open_model_zoo/intel_models/pedestrian-detection-adas-binary-0001/description/pedestrian-detection-adas-binary-0001.png
/usr/share/open_model_zoo/intel_models/person-attributes-recognition-crossroad-0230/description/person-attributes-recognition-crossroad-0230.md
/usr/share/open_model_zoo/intel_models/person-attributes-recognition-crossroad-0230/description/person-attributes-recognition-crossroad-230-1.png
/usr/share/open_model_zoo/intel_models/person-attributes-recognition-crossroad-0230/description/person-attributes-recognition-crossroad-230-2.png
/usr/share/open_model_zoo/intel_models/person-attributes-recognition-crossroad-0230/description/person-attributes-recognition-crossroad-230-3.png
/usr/share/open_model_zoo/intel_models/person-attributes-recognition-crossroad-0230/description/person-attributes-recognition-crossroad-230-4.png
/usr/share/open_model_zoo/intel_models/person-attributes-recognition-crossroad-0230/description/person-attributes-recognition-crossroad-230-5.png
/usr/share/open_model_zoo/intel_models/person-detection-action-recognition-0005/description/person-detection-action-recognition-0005.md
/usr/share/open_model_zoo/intel_models/person-detection-action-recognition-0005/description/person-detection-action-recognition-0005.png
/usr/share/open_model_zoo/intel_models/person-detection-action-recognition-0005/person-detection-action-recognition-0005.prototxt
/usr/share/open_model_zoo/intel_models/person-detection-action-recognition-teacher-0002/description/person-detection-action-recognition-teacher-0002.md
/usr/share/open_model_zoo/intel_models/person-detection-action-recognition-teacher-0002/description/person-detection-action-recognition-teacher-0002.png
/usr/share/open_model_zoo/intel_models/person-detection-action-recognition-teacher-0002/person-detection-action-recognition-teacher-0002.prototxt
/usr/share/open_model_zoo/intel_models/person-detection-raisinghand-recognition-0001/description/person-detection-raisinghand-recognition-0001.md
/usr/share/open_model_zoo/intel_models/person-detection-raisinghand-recognition-0001/description/person-detection-raisinghand-recognition-0001.png
/usr/share/open_model_zoo/intel_models/person-detection-raisinghand-recognition-0001/person-detection-raisinghand-recognition-0001.prototxt
/usr/share/open_model_zoo/intel_models/person-detection-retail-0002/description/person-detection-retail-0002.md
/usr/share/open_model_zoo/intel_models/person-detection-retail-0002/description/person-detection-retail-0002.png
/usr/share/open_model_zoo/intel_models/person-detection-retail-0002/person-detection-retail-0002.prototxt
/usr/share/open_model_zoo/intel_models/person-detection-retail-0013/description/person-detection-retail-0013.md
/usr/share/open_model_zoo/intel_models/person-detection-retail-0013/description/person-detection-retail-0013.png
/usr/share/open_model_zoo/intel_models/person-detection-retail-0013/person-detection-retail-0013.prototxt
/usr/share/open_model_zoo/intel_models/person-reidentification-retail-0031/description/person-reidentification-retail-0031.md
/usr/share/open_model_zoo/intel_models/person-reidentification-retail-0031/description/person-reidentification-retail-0031.png
/usr/share/open_model_zoo/intel_models/person-reidentification-retail-0031/person-reidentification-retail-0031.prototxt
/usr/share/open_model_zoo/intel_models/person-reidentification-retail-0076/description/person-reidentification-retail-0076.md
/usr/share/open_model_zoo/intel_models/person-reidentification-retail-0076/description/person-reidentification-retail-0076.png
/usr/share/open_model_zoo/intel_models/person-reidentification-retail-0076/person-reidentification-retail-0076.prototxt
/usr/share/open_model_zoo/intel_models/person-reidentification-retail-0079/description/person-reidentification-retail-0079.md
/usr/share/open_model_zoo/intel_models/person-reidentification-retail-0079/description/person-reidentification-retail-0079.png
/usr/share/open_model_zoo/intel_models/person-reidentification-retail-0079/person-reidentification-retail-0079.prototxt
/usr/share/open_model_zoo/intel_models/person-vehicle-bike-detection-crossroad-0078/description/person-vehicle-bike-detection-crossroad-0078.md
/usr/share/open_model_zoo/intel_models/person-vehicle-bike-detection-crossroad-0078/description/person-vehicle-bike-detection-crossroad-0078.png
/usr/share/open_model_zoo/intel_models/person-vehicle-bike-detection-crossroad-0078/person-vehicle-bike-detection-crossroad-0078.prototxt
/usr/share/open_model_zoo/intel_models/resnet50-binary-0001/description/resnet50-binary-0001.md
/usr/share/open_model_zoo/intel_models/road-segmentation-adas-0001/description/road-segmentation-adas-0001.md
/usr/share/open_model_zoo/intel_models/road-segmentation-adas-0001/description/road-segmentation-adas-0001.png
/usr/share/open_model_zoo/intel_models/road-segmentation-adas-0001/road-segmentation-adas-0001.prototxt
/usr/share/open_model_zoo/intel_models/semantic-segmentation-adas-0001/description/semantic-segmentation-adas-0001.md
/usr/share/open_model_zoo/intel_models/semantic-segmentation-adas-0001/description/semantic-segmentation-adas-0001.png
/usr/share/open_model_zoo/intel_models/semantic-segmentation-adas-0001/semantic-segmentation-adas-0001.prototxt
/usr/share/open_model_zoo/intel_models/single-image-super-resolution-1032/description/single-image-super-resolution-1032.md
/usr/share/open_model_zoo/intel_models/single-image-super-resolution-1032/description/street_480x270.png
/usr/share/open_model_zoo/intel_models/single-image-super-resolution-1032/description/x4_street_480x270.png
/usr/share/open_model_zoo/intel_models/single-image-super-resolution-1032/description/x4c_street_480x270.png
/usr/share/open_model_zoo/intel_models/single-image-super-resolution-1033/description/single-image-super-resolution-1033.md
/usr/share/open_model_zoo/intel_models/single-image-super-resolution-1033/description/street_640x360.png
/usr/share/open_model_zoo/intel_models/single-image-super-resolution-1033/description/x3_street_640x360.png
/usr/share/open_model_zoo/intel_models/single-image-super-resolution-1033/description/x3c_street_640x360.png
/usr/share/open_model_zoo/intel_models/text-detection-0002/description/text-detection-0002.md
/usr/share/open_model_zoo/intel_models/text-detection-0002/description/text-detection-0002.png
/usr/share/open_model_zoo/intel_models/text-recognition-0012/description/openvino.jpg
/usr/share/open_model_zoo/intel_models/text-recognition-0012/description/text-recognition-0012.md
/usr/share/open_model_zoo/intel_models/vehicle-attributes-recognition-barrier-0039/description/vehicle-attributes-recognition-barrier-0039-1.png
/usr/share/open_model_zoo/intel_models/vehicle-attributes-recognition-barrier-0039/description/vehicle-attributes-recognition-barrier-0039-2.png
/usr/share/open_model_zoo/intel_models/vehicle-attributes-recognition-barrier-0039/description/vehicle-attributes-recognition-barrier-0039.md
/usr/share/open_model_zoo/intel_models/vehicle-attributes-recognition-barrier-0039/vehicle-attributes-recognition-barrier-0039.prototxt
/usr/share/open_model_zoo/intel_models/vehicle-detection-adas-0002/description/vehicle-detection-adas-0002.md
/usr/share/open_model_zoo/intel_models/vehicle-detection-adas-0002/description/vehicle-detection-adas-0002.png
/usr/share/open_model_zoo/intel_models/vehicle-detection-adas-0002/vehicle-detection-adas-0002.prototxt
/usr/share/open_model_zoo/intel_models/vehicle-detection-adas-binary-0001/description/vehicle-detection-adas-binary-0001.md
/usr/share/open_model_zoo/intel_models/vehicle-detection-adas-binary-0001/description/vehicle-detection-adas-binary-0001.png
/usr/share/open_model_zoo/intel_models/vehicle-license-plate-detection-barrier-0106/description/vehicle-license-plate-detection-barrier-0106.jpeg
/usr/share/open_model_zoo/intel_models/vehicle-license-plate-detection-barrier-0106/description/vehicle-license-plate-detection-barrier-0106.md
/usr/share/open_model_zoo/model_downloader/README.md
/usr/share/open_model_zoo/model_downloader/common.py
/usr/share/open_model_zoo/model_downloader/downloader.py
/usr/share/open_model_zoo/model_downloader/license.txt
/usr/share/open_model_zoo/model_downloader/list_topologies.yml

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/open_model_zoo/LICENSE
/usr/share/package-licenses/open_model_zoo/demos_thirdparty_gflags_COPYING.txt
/usr/share/package-licenses/open_model_zoo/intel_models_LICENSE
/usr/share/package-licenses/open_model_zoo/model_downloader_license.txt
